-- Migration: 006_create_resume_analysis.sql
CREATE TABLE IF NOT EXISTS resume_analysis (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    resume_id VARCHAR(64) NULL,
    resume_version_id VARCHAR(64) NULL,
    reference_code VARCHAR(100) NOT NULL UNIQUE,
    target_job_title VARCHAR(150) NULL,
    target_job_description TEXT NULL,
    analysis_type ENUM('ATS', 'CCS', 'ATS_CCS') NOT NULL DEFAULT 'ATS_CCS',
    status ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETYRING') NOT NULL DEFAULT 'COMPLETED',
    approval_status ENUM('PENDING_REVIEW', 'REVIEW_REQUIRED', 'READY_FOR_IMPROVEMENT') NOT NULL DEFAULT 'REVIEW_REQUIRED',
    ats_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    ccs_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    overall_status VARCHAR(50) NOT NULL DEFAULT 'REVIEW_REQUIRED',
    is_approved BOOLEAN NOT NULL DEFAULT FALSE,
    summary TEXT NULL,
    report_data JSON NULL,
    raw_analysis_json JSON NULL,
    gemini_request_id VARCHAR(100) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE SET NULL,
    INDEX idx_resume_analysis_user_id (user_id),
    INDEX idx_resume_analysis_resume_id (resume_id),
    INDEX idx_resume_analysis_status (status),
    INDEX idx_resume_analysis_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
